<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reportingPointTab</name>
   <tag></tag>
   <elementGuidId>18e99693-9570-4fb7-9f98-be6118b166de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/main/app-eagle-sidenavigation/aside/nav/ul/li[2]/ul/li[2]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
