<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateSelectionOptions</name>
   <tag></tag>
   <elementGuidId>f394802e-e54a-4304-bdef-b4222000022d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@&lt;tag> = 'mat-multi-year-view' and (text() = '2014' or . = '2014')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/mat-multi-year-view[@class=&quot;ng-star-inserted&quot;]/table[@role=&quot;presentation&quot;]/tbody[@role=&quot;grid&quot;]/tr[4]/td[2]/div[@class=&quot;mat-calendar-body-cell-content&quot;]/text()</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>&lt;tag></name>
      <type>Main</type>
      <value>mat-multi-year-view</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2014</value>
   </webElementProperties>
</WebElementEntity>
